development:
  clients:
    default:
      database: clark_events_dev
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: clark_events_test
      hosts:
        - localhost:27017
